name: Deploy Website
on:
  push:
    branches:
      - master
jobs:
  Deploy-Website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn docs:build
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: ontop/ontop.github.io
          publish_branch: master 
          publish_dir: .vuepress/dist
